package com.mycompany.st10483276poe_26;

import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

public class MessageTest {
    
    Message message;
    
    @Before
    public void setUp() {
        message = new Message();
        
        // Mock data: ID, Hash, Recipient, Message, Flag
        message.addMockData("ID001", "Hash1", "+27834557896", "Did you get the cake?", "Sent"); //Test data 1
        message.addMockData("ID002", "Hash2", "+27838884567", "Where are you? You are late! I have asked you to be on time.", "Stored"); //Test data 2
        message.addMockData("ID003", "Hash3", "+27834484567", "Yohoooo, I am at your gate.", "Disregard"); //Test data 3
        message.addMockData("0838884567", "Hash4", "0838884567", "It is dinner time !", "Sent"); //Test data 4
        message.addMockData("ID005", "Hash5", "+27838884567", "Ok, I am leaving without you.", "Stored"); //Test data 5                
    }
    
    public MessageTest() {
    }

    //=====================================================
    // Table 1: Test AssertEquals (Part 2)
    //=====================================================
    
    /*
     * Test to verify if a correct message length is used (under 250 char)
     */
    @Test
    public void testMessageLength_Success() {
        String expected = "Message ready to send.";
        String actual = message.checkMessageLength("Hi Mike, can you join us for dinner tonight");
        
        assertEquals(expected, actual);
    }
    
    /*
     * Test to verify if an incorrect message length is used (more than 250 char)
     */
    @Test
    public void testMessageLength_Failure() {
        String longMessage = "A".repeat(251);
        String expected = "Message exceeding 250 characters by 1; please reduce the size.";
        String actual = message.checkMessageLength(longMessage);
        
        assertEquals(expected, actual);
    }    

    //------------------ Recipient Form Test ------------------
    
    /*
     * Test to verify if a cellphone number meet the required conditions (South African formatat +27)
     */    
    @Test
    public void testRecipientNumber_Success() {
        String expected = "Cellphone number successfully captured.";
        String actual = message.checkrecipientCell("+27838968976");
        
        assertEquals(expected, actual);
    }

    /*
     * Tests if an incorrect phone number format returns false
     */     
    @Test
    public void testRecipientNumber_Failure() {
        String expected = "Incorrect cellphone format! please try again and make sure your have the correct format and your internation code is a South African number starting with +27.";
        String actual = message.checkrecipientCell("08966553");
        
        assertEquals(expected, actual);
    }
    
    //------------------ Message Hash Test ------------------

    /*
     * Test to verify if the autogenerated hash is correct 
     */         
    @Test
    public void testMessageHash_Correct() {
        message.checkMessageLength("Hi Mike, can you join us for dinner tonight"); 
        
        String firstTwo = message.getMessageID().substring(0,2); 
        String expectedHash = firstTwo + ":0:HITONIGHT";
        
        String actualHash = message.getmessageHash();
        
        assertEquals(expectedHash, actualHash);
    }

    //------------------ Send Message Option Test ------------------
    
    /*
     * Test Option 1:
     * Send Message
     */     
    @Test
    public void testSendMessage_Send() {
        // FIXED: Added the period at the end
        String expected = "Message successfully sent.";        
        String actual = message.SentMessage(1);  
        
        assertEquals(expected, actual);
    }
    /*
    
     * Test Option 2:
     * Discard Messasge
     */ 
    @Test
    public void testSendMessage_Discard() {
        String expected = "Press 0 to delete the message.";        
        String actual = message.SentMessage(2);  
        
        assertEquals(expected, actual);        
    }
    
    /*
     * Test Option 3:
     * Store Message
     */ 
    @Test
        public void testSendMessage_Store() {
        String expected = "Message successfully stored.";        
        String actual = message.SentMessage(3);  
        
        assertEquals(expected, actual);        
    }
        
    //=====================================================
    // Table 2: Manager Logic Tests (Part 3)
    //=====================================================
        
    /*
    * Test 1: Sent messages array correctely populated
    * Expected: "Did you get the cake?" , "It is dinner time!" 
    */
    @Test
    public void testSentMessagesArrayCorrectlyPopulated() { // public method
        String sentMessages = message.getAllSentMessages();
        assertTrue(sentMessages.contains("Did you get the cake?"));
        assertTrue(sentMessages.contains("It is dinner time !"));
    }
    
    /*
    * Test 2: Display the longest message 
    * Expected: "Where are you? You are late! I have asked you to be on time."
    */
    @Test
    public void testDisplayLongestMessage() { // public method
        String longestMessage = message.getLongestMessage();
        assertEquals("Where are you? You are late! I have asked you to be on time.", longestMessage);
    }
    
    /*
    * Test 3: Search for messageID
    * Expected: "It is dinner time !" (Using Developer ID 0838884567)
    */
    @Test
    public void testSearchForMessageID() { // public method
        String foundMessage = message.searchMessageByID("0838884567");
        assertEquals("It is dinner time !", foundMessage);
    }

    /*
    * Test 4: Search all messages regarding a particular recipient 
    * Expected: Returns both messages for +27838884567
    */    
    @Test
    public void testSearchByRecipient() { // public method
        String recipientMessages = message.searchByRecipient("+27838884567");
        assertTrue(recipientMessages.contains("Where are you? You are late! I have asked you to be on time."));
        assertTrue(recipientMessages.contains("Ok, I am leaving without you."));        
    }

    /*
    * Test 5: Delete a message using a message hash
    * Expected: Message: "[Message Text]" successfully deleted.
    */    
    @Test
    public void testDeleteMessageUsingHash() { // public method
        // The 2nd message is deleted using the mock hash "Hash2"
        String deleteResult = message.deleteMessageByHash("Hash2");
        String expectedOutput = "Message: \"Where are you? You are late! I have asked you to be on time.\" successfully deleted.";
        assertEquals(expectedOutput, deleteResult);
    }    
        
}